version: "3.6"
services:
  web:
      build: .
#      image: sezzle/magento2:1.0
      ports:
      - "8085:80"
      links:
        - db
      volumes:
      - .:/var/www/html/app/code/Sezzle/Sezzlepay
      env_file:
        - docker.env
  db:
      image: mysql:5.6.23
      volumes:
          - db-data:/var/lib/mysql/data
      env_file:
          - docker.env
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      ports:
          - "8580:80"
      links:
          - db
volumes:
  db-data:
